package Accounting.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64eaa54L, "Accounting.structure.Company"))) {
        return Collections.<ConceptEditor>singletonList(new Company_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64ec55dL, "Accounting.structure.Date"))) {
        return Collections.<ConceptEditor>singletonList(new Date_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db1f7L, "Accounting.structure.EntitiesGroup"))) {
        return Collections.<ConceptEditor>singletonList(new EntitiesGroup_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL, "Accounting.structure.Invoice"))) {
        return Collections.<ConceptEditor>singletonList(new Invoice_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db08aL, "Accounting.structure.InvoiceLine"))) {
        return Collections.<ConceptEditor>singletonList(new InvoiceLine_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02eL, "Accounting.structure.InvoicesGroup"))) {
        return Collections.<ConceptEditor>singletonList(new InvoicesGroup_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db090L, "Accounting.structure.Money"))) {
        return Collections.<ConceptEditor>singletonList(new Money_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db1f0L, "Accounting.structure.Percentage"))) {
        return Collections.<ConceptEditor>singletonList(new Percentage_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db03aL, "Accounting.structure.VATIdentifier"))) {
        return Collections.<ConceptEditor>singletonList(new VATIdentifier_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
