package Accounting.behavior;

/*Generated by MPS */

import java.math.BigDecimal;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Invoice_Behavior {
  public static BigDecimal call_totalAmount_4989694486378979358(SNode __thisNode__) {
    return Invoice__BehaviorDescriptor.totalAmount_id4kYXbbAm20u(__thisNode__);
  }
  public static BigDecimal call_totalVATAmount_4989694486378992251(SNode __thisNode__) {
    return Invoice__BehaviorDescriptor.totalVATAmount_id4kYXbbAm59V(__thisNode__);
  }
  public static BigDecimal call_total_4989694486378995234(SNode __thisNode__) {
    return Invoice__BehaviorDescriptor.total_id4kYXbbAm5Sy(__thisNode__);
  }
}
