package Accounting.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.BehaviorRegistry;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import java.math.BigDecimal;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IRightCombinator;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;

public final class Invoice__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL, "Accounting.structure.Invoice");
  private static final BehaviorRegistry REGISTRY = ConceptRegistry.getInstance().getBehaviorRegistry();

  public static final SMethod<BigDecimal> totalAmount_id4kYXbbAm20u = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("totalAmount").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("4kYXbbAm20u").registry(REGISTRY).build();
  public static final SMethod<BigDecimal> totalVATAmount_id4kYXbbAm59V = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("totalVATAmount").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("4kYXbbAm59V").registry(REGISTRY).build();
  public static final SMethod<BigDecimal> total_id4kYXbbAm5Sy = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("total").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("4kYXbbAm5Sy").registry(REGISTRY).build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(totalAmount_id4kYXbbAm20u, totalVATAmount_id4kYXbbAm59V, total_id4kYXbbAm5Sy);

  private static void ___init___(@NotNull SNode __thisNode__) {
    SLinkOperations.addNewChild(__thisNode__, MetaAdapterFactory.getContainmentLink(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL, 0x453ef4b2e64ee0d4L, "lines"), SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db08aL, "Accounting.structure.InvoiceLine")));
  }

  /*package*/ static BigDecimal totalAmount_id4kYXbbAm20u(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, MetaAdapterFactory.getContainmentLink(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL, 0x453ef4b2e64ee0d4L, "lines"))).foldRight(BigDecimal.ZERO, new IRightCombinator<SNode, BigDecimal>() {
      public BigDecimal combine(SNode it, BigDecimal s) {
        return Money__BehaviorDescriptor.asBigDecimal_id4kYXbbAlowJ.invoke(SLinkOperations.getTarget(it, MetaAdapterFactory.getContainmentLink(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db08aL, 0x453ef4b2e64db1eeL, "amount"))).add(s);
      }
    });
  }
  /*package*/ static BigDecimal totalVATAmount_id4kYXbbAm59V(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, MetaAdapterFactory.getContainmentLink(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL, 0x453ef4b2e64ee0d4L, "lines"))).foldRight(BigDecimal.ZERO, new IRightCombinator<SNode, BigDecimal>() {
      public BigDecimal combine(SNode it, BigDecimal s) {
        return InvoiceLine__BehaviorDescriptor.vatAmount_id4kYXbbAlngZ.invoke(it).add(s);
      }
    });
  }
  /*package*/ static BigDecimal total_id4kYXbbAm5Sy(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, MetaAdapterFactory.getContainmentLink(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL, 0x453ef4b2e64ee0d4L, "lines"))).foldRight(BigDecimal.ZERO, new IRightCombinator<SNode, BigDecimal>() {
      public BigDecimal combine(SNode it, BigDecimal s) {
        return InvoiceLine__BehaviorDescriptor.total_id4kYXbbAlvrI.invoke(it).add(s);
      }
    });
  }

  /*package*/ Invoice__BehaviorDescriptor() {
    super(REGISTRY);
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((BigDecimal) totalAmount_id4kYXbbAm20u(node));
      case 1:
        return (T) ((BigDecimal) totalVATAmount_id4kYXbbAm59V(node));
      case 2:
        return (T) ((BigDecimal) total_id4kYXbbAm5Sy(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
}
