package Accounting.behavior;

/*Generated by MPS */

import java.math.BigDecimal;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class InvoiceLine_Behavior {
  public static BigDecimal call_vatAmount_4989694486378804287(SNode __thisNode__) {
    return InvoiceLine__BehaviorDescriptor.vatAmount_id4kYXbbAlngZ(__thisNode__);
  }
  public static BigDecimal call_total_4989694486378837742(SNode __thisNode__) {
    return InvoiceLine__BehaviorDescriptor.total_id4kYXbbAlvrI(__thisNode__);
  }
}
