package Accounting.behavior;

/*Generated by MPS */

import java.math.BigDecimal;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Money_Behavior {
  public static BigDecimal call_asBigDecimal_4989694486378809391(SNode __thisNode__) {
    return Money__BehaviorDescriptor.asBigDecimal_id4kYXbbAlowJ(__thisNode__);
  }
}
