package Accounting.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Currency {
  EURO("EURO", "EURO");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Currency(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Currency> getConstants() {
    List<Currency> list = ListSequence.fromList(new LinkedList<Currency>());
    ListSequence.fromList(list).addElement(Currency.EURO);
    return list;
  }
  public static Currency getDefault() {
    return Currency.EURO;
  }
  public static Currency parseValue(String value) {
    if (value == null) {
      return Currency.getDefault();
    }
    if (value.equals(Currency.EURO.getValueAsString())) {
      return Currency.EURO;
    }
    return Currency.getDefault();
  }
}
