package Accounting.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Month {
  JAN("JAN", 1),
  FEB("FEB", 2),
  MAR("MAR", 3),
  APR("APR", 4),
  MAY("MAY", 5),
  JUN("JUN", 6),
  JUL("JUL", 7),
  AUG("AUG", 8),
  SEP("SEP", 9),
  OCT("OCT", 10),
  NOV("NOV", 11),
  DEC("DEC", 12);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  Month(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<Month> getConstants() {
    List<Month> list = ListSequence.fromList(new LinkedList<Month>());
    ListSequence.fromList(list).addElement(Month.JAN);
    ListSequence.fromList(list).addElement(Month.FEB);
    ListSequence.fromList(list).addElement(Month.MAR);
    ListSequence.fromList(list).addElement(Month.APR);
    ListSequence.fromList(list).addElement(Month.MAY);
    ListSequence.fromList(list).addElement(Month.JUN);
    ListSequence.fromList(list).addElement(Month.JUL);
    ListSequence.fromList(list).addElement(Month.AUG);
    ListSequence.fromList(list).addElement(Month.SEP);
    ListSequence.fromList(list).addElement(Month.OCT);
    ListSequence.fromList(list).addElement(Month.NOV);
    ListSequence.fromList(list).addElement(Month.DEC);
    return list;
  }
  public static Month getDefault() {
    return Month.JAN;
  }
  public static Month parseValue(String value) {
    if (value == null) {
      return Month.getDefault();
    }
    if (value.equals(Month.JAN.getValueAsString())) {
      return Month.JAN;
    }
    if (value.equals(Month.FEB.getValueAsString())) {
      return Month.FEB;
    }
    if (value.equals(Month.MAR.getValueAsString())) {
      return Month.MAR;
    }
    if (value.equals(Month.APR.getValueAsString())) {
      return Month.APR;
    }
    if (value.equals(Month.MAY.getValueAsString())) {
      return Month.MAY;
    }
    if (value.equals(Month.JUN.getValueAsString())) {
      return Month.JUN;
    }
    if (value.equals(Month.JUL.getValueAsString())) {
      return Month.JUL;
    }
    if (value.equals(Month.AUG.getValueAsString())) {
      return Month.AUG;
    }
    if (value.equals(Month.SEP.getValueAsString())) {
      return Month.SEP;
    }
    if (value.equals(Month.OCT.getValueAsString())) {
      return Month.OCT;
    }
    if (value.equals(Month.NOV.getValueAsString())) {
      return Month.NOV;
    }
    if (value.equals(Month.DEC.getValueAsString())) {
      return Month.DEC;
    }
    return Month.getDefault();
  }
}
