package Accounting.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptCompany = new ConceptDescriptorBuilder("Accounting.structure.Company", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64eaa54L)).super_("Accounting.structure.Entity").super_(MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db037L)).parents("Accounting.structure.Entity").parentIds(MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db037L)).childDescriptors(new ConceptDescriptorBuilder.Link(4989694486378295797L, "vatID", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db03aL), false, false, false)).children(new String[]{"vatID"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptDate = new ConceptDescriptorBuilder("Accounting.structure.Date", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64ec55dL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378366304L, "day"), new ConceptDescriptorBuilder.Prop(4989694486378366302L, "month"), new ConceptDescriptorBuilder.Prop(4989694486378366312L, "year")).properties("day", "month", "year").create();
  /*package*/ final ConceptDescriptor myConceptEntitiesGroup = new ConceptDescriptorBuilder("Accounting.structure.EntitiesGroup", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db1f7L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(4989694486378295802L, "entities", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db037L), true, true, false)).children(new String[]{"entities"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptEntity = new ConceptDescriptorBuilder("Accounting.structure.Entity", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db037L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378359368L, "address")).properties("address").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptInvoice = new ConceptDescriptorBuilder("Accounting.structure.Invoice", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378295426L, "year"), new ConceptDescriptorBuilder.Prop(4989694486378295424L, "identifier")).properties("year", "identifier").referenceDescriptors(new ConceptDescriptorBuilder.Ref(4989694486378295431L, "emitter", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db037L), false), new ConceptDescriptorBuilder.Ref(4989694486378295429L, "client", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db037L), false)).references("emitter", "client").childDescriptors(new ConceptDescriptorBuilder.Link(4989694486378366695L, "emittedOn", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64ec55dL), false, false, false), new ConceptDescriptorBuilder.Link(4989694486378373332L, "lines", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db08aL), false, true, false)).children(new String[]{"emittedOn", "lines"}, new boolean[]{false, true}).create();
  /*package*/ final ConceptDescriptor myConceptInvoiceLine = new ConceptDescriptorBuilder("Accounting.structure.InvoiceLine", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db08aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378295435L, "description")).properties("description").childDescriptors(new ConceptDescriptorBuilder.Link(4989694486378295790L, "amount", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db090L), false, false, false), new ConceptDescriptorBuilder.Link(4989694486378381448L, "vatRate", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db1f0L), false, false, false)).children(new String[]{"amount", "vatRate"}, new boolean[]{false, false}).create();
  /*package*/ final ConceptDescriptor myConceptInvoicesGroup = new ConceptDescriptorBuilder("Accounting.structure.InvoicesGroup", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02eL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(4989694486378295357L, "invoices", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db02fL), true, true, false)).children(new String[]{"invoices"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptMoney = new ConceptDescriptorBuilder("Accounting.structure.Money", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db090L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378295443L, "integerPart"), new ConceptDescriptorBuilder.Prop(4989694486378295445L, "decimalPart"), new ConceptDescriptorBuilder.Prop(4989694486378295456L, "currency")).properties("integerPart", "decimalPart", "currency").create();
  /*package*/ final ConceptDescriptor myConceptPercentage = new ConceptDescriptorBuilder("Accounting.structure.Percentage", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db1f0L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378389745L, "value")).properties("value").create();
  /*package*/ final ConceptDescriptor myConceptVATIdentifier = new ConceptDescriptorBuilder("Accounting.structure.VATIdentifier", MetaIdFactory.conceptId(0x3511d2b0c9d74a02L, 0xa20bca10f21445c3L, 0x453ef4b2e64db03aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4989694486378354579L, "identifier")).properties("identifier").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCompany, myConceptDate, myConceptEntitiesGroup, myConceptEntity, myConceptInvoice, myConceptInvoiceLine, myConceptInvoicesGroup, myConceptMoney, myConceptPercentage, myConceptVATIdentifier);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0o, conceptFqName)) {
      case 0:
        return myConceptCompany;
      case 1:
        return myConceptDate;
      case 2:
        return myConceptEntitiesGroup;
      case 3:
        return myConceptEntity;
      case 4:
        return myConceptInvoice;
      case 5:
        return myConceptInvoiceLine;
      case 6:
        return myConceptInvoicesGroup;
      case 7:
        return myConceptMoney;
      case 8:
        return myConceptPercentage;
      case 9:
        return myConceptVATIdentifier;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0o = new String[]{"Accounting.structure.Company", "Accounting.structure.Date", "Accounting.structure.EntitiesGroup", "Accounting.structure.Entity", "Accounting.structure.Invoice", "Accounting.structure.InvoiceLine", "Accounting.structure.InvoicesGroup", "Accounting.structure.Money", "Accounting.structure.Percentage", "Accounting.structure.VATIdentifier"};
}
